blogger/urls.py
from django.urls import path

from . import views

app_name = 'blogger'
urlpatterns = [
    path('', views.login, name='login'),
    path('create', views.create, name='create'),
    path('help', views.help, name='help'),
    path('index', views.index, name='index'),
    path('index_view/<str:id>', views.index_view, name='index_view'),
    path('profile', views.profile, name='profile'),
    path('user/<str:id>', views.user, name='user'),
    path('delete', views.delete, name='delete'),
    path('add_link', views.add_link, name='add_link'),
    path('link/<str:id>', views.link, name='link'),
    path('logout', views.logout, name='logout'),
    path('network_json', views.network_json),
    path('post/<str:id>', views.page, name='page'),
]

networkvis/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('blogger.urls')),
    path('admin/', admin.site.urls),
]

# serve static files during development
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blogger/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField


# the setting on the 'index' page (to decide which network to show)
class Setting(models.Model):
    SETTING_CHOICES = [
        ('empty', 'empty'),
        ('sample', 'sample'),
        ('main', 'main'),
    ]
    setting = models.CharField(max_length=100, choices=SETTING_CHOICES)


# ArrayField requires a function for default
def admin():
    return ['admin']


class Page(models.Model):
    title = models.CharField(max_length=30)
    # stores User id's
    authors = ArrayField(models.CharField(max_length=10), default=admin)
    description = models.CharField(max_length=300)
    color = models.CharField(max_length=20)
    desc_color = models.CharField(max_length=20, default='#444444')
    content = models.TextField()


class Link(models.Model):
    # stores Page id's
    source = models.CharField(max_length=10)
    target = models.CharField(max_length=10)
    authors = ArrayField(models.CharField(max_length=10), default=admin)
    color = models.CharField(max_length=20)
    description = models.CharField(default='', max_length=300)
    desc_color = models.CharField(max_length=20, default='#444444')
    content = models.TextField(default='')


class User(models.Model):
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=100)
    # verbose_name = 'display name'
    name = models.CharField('display name', max_length=100)

blogger/forms.py
from django import forms
from .models import Setting, Page, Link, User


# form to set setting (determines which network is displayed)
class SettingForm(forms.ModelForm):
    class Meta:
        model = Setting
        fields = ['setting']


# form to add page (appears when '+' button on node is clicked)
class AddPageForm(forms.ModelForm):
    class Meta:
        model = Page
        fields = ['title', 'description', 'color', 'content']


# general delete confirmation form
class DelForm(forms.Form):
    field = forms.CharField(label='', max_length=30)


# general delete confirmation form with password
class DelFormPassword(forms.Form):
    field = forms.CharField(label='', max_length=30, widget=forms.PasswordInput)


# login form
class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']
        widgets = {
            'password': forms.PasswordInput(),
        }


# create new user form
class CreateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password', 'name']
        widgets = {
            'password': forms.PasswordInput(),
        }


# change display name form
class ChangeNameForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['name']


# change password form (have to input old password as well)
class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(max_length=100, widget=forms.PasswordInput)
    new_password = forms.CharField(max_length=100, widget=forms.PasswordInput)


# add link form
class AddLinkForm(forms.ModelForm):
    class Meta:
        model = Link
        fields = ['source', 'target', 'color']

blogger/views.py
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.shortcuts import render, get_object_or_404
from .models import Setting, Page, Link, User
from .forms import SettingForm, AddPageForm, DelForm, DelFormPassword, LoginForm, CreateForm, ChangeNameForm, ChangePasswordForm, AddLinkForm
# AddLinkForm (deprecated)
# framework for sending alerts to users
from django.contrib import messages
# hashing passwords!
from django.contrib.auth import hashers

import requests, json, markdown


# login page
def login(request):
    # process login form
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            # check if username exists
            if not User.objects.filter(username=form.cleaned_data['username']):
                # messages is a framework that sends alert(s) to the user
                messages.error(request, 'Username not found')
                return HttpResponseRedirect(reverse('blogger:login'))
            # check password
            u = User.objects.get(username=form.cleaned_data['username'])
            if hashers.check_password(form.cleaned_data['password'], u.password):
                # this is how we know which user is logged in
                request.session['user'] = u.id
                # this stuff is to determine which button(s) to display on the
                # 'help' page
                request.session['helped'] = 'index'
                messages.success(request, 'Welcome ' + u.name + '!')
                return HttpResponseRedirect(reverse('blogger:index'))
            else:
                messages.error(request, 'Incorrect password')
                return HttpResponseRedirect(reverse('blogger:login'))
    request.session['helped'] = 'login'
    login_form = LoginForm()
    return render(request, 'blogger/login.html', {
        'login_form': login_form,
    })


# create new user page
def create(request):
    # process create user form
    if request.method == 'POST':
        form = CreateForm(request.POST)
        if form.is_valid():
            # check if username has been taken
            if User.objects.filter(username=form.cleaned_data['username']):
                messages.error(request, 'Username already taken')
                return HttpResponseRedirect(reverse('blogger:create'))
            u = form.save()
            u.password = hashers.make_password(u.password)
            u.save()
            # this is how we know which user is logged in
            request.session['user'] = u.id
            messages.success(request, 'Welcome ' + u.name + '!')
            # go to 'index' if user has already seen 'help' page, 'help' otherwise
            if request.session['helped'] == 'helped':
                return HttpResponseRedirect(reverse('blogger:index'))
            else:
                request.session['helped'] = 'helped'
                return HttpResponseRedirect(reverse('blogger:help'))
    create_form = CreateForm()
    return render(request, 'blogger/create.html', {
        'create_form': create_form,
    })


# help page
def help(request):
    temp = request.session['helped']
    # bug: if the user reloads the page, the button will change from 'Get started'
    # to 'Onward!'
    request.session['helped'] = 'helped'
    return render(request, 'blogger/help.html', {'helped': temp})


# index page (displays network)
def index(request):
    if 'user' not in request.session:
        return index_view(request)
    u = User.objects.get(id=request.session['user'])
    # request.session['page'] tells us which page to go back to if the user got
    # to a page via another
    request.session['page'] = None
    # determine which button(s) to display on the 'help' page
    if request.session['helped'] == 'helped':
        request.session['helped'] = 'index'
    # process form, whichever was submitted
    if request.method == 'POST':
        # process setting_form
        if 'setting_form' in request.POST:
            # via Django ModelForm we can modify models easily
            # this says to change the model instance according to the form
            form = SettingForm(request.POST, instance=Setting.objects.all()[0])
            if form.is_valid():
                form.save()
        # process add_page_form
        elif 'add_page_form' in request.POST:
            id = request.POST['id']
            form = AddPageForm(request.POST)
            if form.is_valid():
                # this says to save a new model instance according to the form
                p = form.save()
                # add user to p.authors
                p.authors = [u.id]
                p.save()
                # add new link based on the node that the add_page_form was
                # submitted from
                Link(source=id, target=p.id, color='green').save()
                messages.success(request, 'Page added successfully')
        # process add_link_form (it's the same AddPageForm but you click the
        # 'Link' button instead)
        elif 'add_link_form' in request.POST:
            id = request.POST['id']
            form = AddPageForm(request.POST)
            if form.is_valid():
                if not Page.objects.filter(title=form.cleaned_data['title']):
                    messages.error(request, 'Page not found')
                    return HttpResponseRedirect(reverse('blogger:index'))
                target = Page.objects.get(title=form.cleaned_data['title']).id
                l = Link(source=id, target=target, authors=[u.id], \
                    color=form.cleaned_data['color'], \
                    description=form.cleaned_data['description'], \
                    content=form.cleaned_data['content'])
                l.save()
                messages.success(request, 'Link added successfully')
        # process del_page_form
        elif 'del_page_form' in request.POST:
            id = request.POST['id']
            form = DelForm(request.POST)
            if form.is_valid():
                # delete page and all links that include the page
                Page.objects.get(id=id).delete()
                l_set = Link.objects.filter(source=id) | Link.objects.filter(target=id)
                for link in l_set:
                    link.delete()
                messages.success(request, 'Page deleted successfully')
        return HttpResponseRedirect(reverse('blogger:index'))
    else:
        setting_form = SettingForm()
        add_page_form = AddPageForm()
        del_page_form = DelForm()
        return render(request, 'blogger/index.html', {
                'setting_form': setting_form,
                'add_page_form': add_page_form,
                'del_page_form': del_page_form,
            })


# if user is not logged in, view only
def index_view(request):
    request.session['helped'] = 'index'
    return render(request, 'blogger/index.html', {
        'view': True,
    })


# profile page
def profile(request):
    u = User.objects.get(id=request.session['user'])
    if request.method == 'POST':
        # process name_form
        if 'name_form' in request.POST:
            # change the user instance according to the form
            form = ChangeNameForm(request.POST, instance=u)
            if form.is_valid():
                form.save()
                messages.success(request, 'Display name changed successfully')
        # process password_form
        elif 'password_form' in request.POST:
            form = ChangePasswordForm(request.POST)
            if form.is_valid():
                # if old password matches, set password to new password
                if not hashers.check_password(form.cleaned_data['old_password'], u.password):
                    messages.error(request, 'Incorrect old password')
                else:
                    u.password = hashers.make_password(form.cleaned_data['new_password'])
                    u.save()
                    messages.success(request, 'Password changed successfully')
        return HttpResponseRedirect(reverse('blogger:profile'))
    change_name_form = ChangeNameForm()
    change_password_form = ChangePasswordForm()
    return render(request, 'blogger/profile.html', {
        'name': u.name,
        'username': u.username,
        'change': True,
        'page': request.session['page'],
        'link': request.session['link'],
        'name_form': change_name_form,
        'password_form': change_password_form,
    })


# view user page (similar to profile page but with no edit capabilities)
def user(request, id):
    # if it's the user that's logged in, just redirect to their profile page
    if int(id) == request.session['user']:
        return HttpResponseRedirect(reverse('blogger:profile'))
    u = User.objects.get(id=id)
    return render(request, 'blogger/profile.html', {
        'name': u.name,
        'username': u.username,
        'change': False,
        'page': request.session['page'],
        'link': request.session['link'],
    })


# delete user confirmation page
def delete(request):
    # process delete user confirmation form
    if request.method == 'POST':
        u = User.objects.get(id=request.session['user'])
        form = DelFormPassword(request.POST)
        if form.is_valid():
            # if password is wrong, redirect
            if not hashers.check_password(form.cleaned_data['field'], u.password):
                messages.error(request, 'Incorrect password')
                return HttpResponseRedirect(reverse('blogger:delete'))
            # else delete + logout
            u.delete()
            request.session.flush()
            messages.success(request, 'User deleted successfully')
            return HttpResponseRedirect(reverse('blogger:login'))
    del_user_form = DelFormPassword()
    return render(request, 'blogger/delete.html', {
        'del_user_form': del_user_form,
    })


# add link page
def add_link(request):
    # process add link form

blogger/templates/blogger/add_link.html
<!-- deprecated -->
{% load static %}

<head>
  <link rel='stylesheet' type='text/css' href='{% static "blogger/blocks.css" %}' />
  <link rel='icon' type='image/png' href='https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Banana-Single.jpg/1200px-Banana-Single.jpg'>
  <title> add link </title>
</head>

<body class='flex'>
  <!-- display messages -->
  {% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}

  <!-- create user form -->
  <div class='main section padded'>
    <h1> Add new link: </h1>
    <form action='{% url "blogger:add_link" %}' method='post' autocomplete='off'>
      {% csrf_token %}
      {{ add_link_form|linebreaks }}
      <input type='submit' name='add_link_form' value='Add'>
    </form>
  </div>
  <div class='buttons'>
    <!-- back to login -->
    <a href='{% url "blogger:index" %}'>
      <div class='section button'>
        Back to index
      </div>
    </a>
  </div>
</body>

blogger/templates/blogger/create.html
{% load static %}

<head>
  <link rel='stylesheet' type='text/css' href='{% static "blogger/blocks.css" %}' />
  <link rel='icon' type='image/png' href='https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Banana-Single.jpg/1200px-Banana-Single.jpg'>
  <title> create </title>
</head>

<body class='flex'>
  {% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}

  <div class='main section padded'>
    <h1> Create your account: </h1>
    <form action='{% url "blogger:create" %}' method='post' autocomplete='off'>
      {% csrf_token %}
      {{ create_form|linebreaks }}
      <input type='submit' name='create_form' value='Create'>
    </form>
  </div>
  <div class='buttons'>
    <a href='{% url "blogger:login" %}'>
      <div class='section button'>
        Back
      </div>
    </a>
  </div>
</body>

blogger/templates/blogger/delete.html
{% load static %}

<head>
  <link rel='stylesheet' type='text/css' href='{% static "blogger/blocks.css" %}' />
  <link rel='icon' type='image/png' href='https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Banana-Single.jpg/1200px-Banana-Single.jpg'>
  <title> delete </title>
</head>

<body class='flex'>
  <!-- display messages -->
  {% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}

  <!-- delete user confirmation form (will redirect back here if password
  incorrect) -->
  <div class='main section padded'>
    <h1> Are you sure you want to delete your account? Type your password below to confirm: </h1>
    <form action='{% url "blogger:delete" %}' method='post' autocomplete='off'>
      {% csrf_token %}
      {{ del_user_form|linebreaks }}
      <input id='del-submit' type='submit' name='del_user_form' value='Delete'>
    </form>
  </div>
  <div class='buttons'>
    <a href='{% url "blogger:profile" %}'>
      <div class='section button'>
        Back to user profile
      </div>
    </a>
  </div>
</body>

blogger/templates/blogger/help.html
{% load static %}

<head>
  <link rel='stylesheet' type='text/css' href='{% static "blogger/blocks.css" %}' />
  <link rel='icon' type='image/png' href='https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Banana-Single.jpg/1200px-Banana-Single.jpg'>
  <title> help </title>
</head>

<body class='flex'>
  <!-- display messages -->
  {% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}

  <!-- a helpful tutorial -->
  <div class='main section padded'>
    <h1> About </h1>
    <p> <strong> NetVis Blogger </strong> is a combined blogger, mind mapper,
    and network visualizer.
    Its format is like a regular blogger - one can write as well as style posts
    - but users are able to see visually how the pages are connected, giving the
    pasttime of blogging an entirely new feel.
    In addition, users are encouraged to collaborate on blog posts, allowing
    them to build off of each other's ideas in a very visual way. </p>
  </div>
  <div class='main section padded'>
    <p> The main view of a blog looks like this: </p>
    <img src='{% static "blogger/network-vis.png "%}' />
    <p> (As of now, there is only one blog 'main', though the intention is to
    eventually allow for both personal and group-run blogs.)
    Each node represents a single post, which contains a title, a
    description, and content.
    The titles are displayed on the nodes, as shown.
    To see the node's description, click on the title text, and the node will
    expand, showing the description in the middle. </p>
  </div>
  <div class='main section padded'>
    <p> The title is not a node's only clickable item: there are also "+" and "-"
    buttons hidden on the bottom and top, respectively.
    If you mouse over them, they will appear.
    Their functions are to create a new node and delete the node, respectively.
    Upon being clicked, the node will expand to show the corresponding form for
    adding or deleting a node. </p>
  </div>
  <div class='main section padded'>
    <p> When expanding a node via its title, you will notice a link saying
    "Visit page."
    As would make sense, the link goes to the post page, displaying the title,
    the authors, the description, and the content, like this:</p>
    <img src='{% static "blogger/network-vis-2.png "%}' />
    <p style='margin-bottom: 0;'> If none of the authors is 'admin-frozen' and one of the following are true: </p>
    <div style='display: inline-block;'>
      <ul>
        <li> you are one of the authors
        <li> one of the authors is 'admin'
      </ul>
    </div>
    <p style='margin-top: 0;'> you will be able to edit the page's content.
    If the first is true, then you will also be able to give any user edit
    permission by clicking the '+' button.
    The description and the content sections support John Gruber's
    <a href='https://en.wikipedia.org/wiki/Markdown'> Markdown</a>.
    The bottom row of buttons is also important: the first two set the
    background colors of the title and the description, respectively, and the
    last three do what they say.
    The "Save changes" button is highlighted because it is very important: be
    sure to save your changes before leaving the page! </p>
  </div>
  <div class='main section padded'>
    <p> Of course, nodes are nothing without links connecting them together.
    Whenever a new node is created from another node, a green link is connected
    between the two nodes.
    Also, you can create custom links via the "Add link" button on a blog's main
    view, which will be added to the two posts' pages. </p>
  </div>
  <div class='main section padded'>
    <p> Finally, there are basic user management functions, such as changing the
    display name, changing the password, and deleting the account. More user
    customization is coming soon! </p>
  </div>
  <!-- determine which buttons to show based on 'helped' (a variable depending
  on where the user has been) -->
  <div class='buttons'>
    {% if helped == 'index' %}
    <a href='{% url "blogger:index" %}'>
      <div class='section button'>
        Back to index
      </div>
    </a>
    {% else %}
    <a href='{% url "blogger:login" %}'>
      <div class='section button'>
        Back to login
      </div>
    </a>
      {% if helped == 'helped' %}
      <!-- go to 'index' page -->
      <a href='{% url "blogger:index" %}'>
        <div class='section button'>
          Onward!
        </div>
      </a>
      {% elif helped == 'login' %}
      <!-- go to 'create' page -->
      <a href='{% url "blogger:create" %}'>
        <div class='section button'>
          Get started
        </div>
      </a>
      {% endif %}
    {% endif %}
  </div>
</body>

blogger/templates/blogger/index.html
{% load static %}

<head>
  <script src='https://d3js.org/d3.v5.min.js'></script>
  <script src="https://d3js.org/d3-fetch.v1.min.js"></script>
  <link rel='stylesheet' type='text/css' href='{% static "blogger/index.css" %}' />
  <link rel='icon' type='image/png' href='https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Banana-Single.jpg/1200px-Banana-Single.jpg'>
  <title> index </title>
</head>

<body>
  {% if view %}
  {% else %}
  <!-- display messages -->
  {% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}

  <!-- form to set setting (which determines which network to display) -->
  <form action='{% url "blogger:index" %}' method='post'>
    {% csrf_token %}
    {{ setting_form }}
    <input type='submit' name='setting_form' value='Change'>
  </form>
  <!-- go to 'help' page -->
  <a class='nodecor' href='{% url "blogger:help" %}'>
    <div class='section button'>
      Help
    </div>
  </a>
  <!-- go to 'profile' page -->
  <a class='nodecor' href='{% url "blogger:profile" %}'>
    <div class='section button'>
      User profile
    </div>
  </a>
  <br>
  <!-- go to 'link' page -->
  <a class='nodecor' href='{% url "blogger:add_link" %}'>
    <div class='section button'>
      Add link
    </div>
  </a>
  <!-- logout (redirects to login) -->
  <a class='nodecor' href='{% url "blogger:logout" %}'>
    <div class='section button'>
      Logout
    </div>
  </a>
  {% endif %}

  <div id='graph'>
  </div>
  <script type='text/javascript'>
    var formAction = '{% url "blogger:index" %}';
    var addPageForm = '{% csrf_token %}' + '{{ add_page_form|addslashes|linebreaks }}';
    var delPageForm = '{% csrf_token %}' + '{{ del_page_form|addslashes|linebreaks }}';
  </script>
  <script src='{% static "blogger/index.js" %}'></script>
</body>

blogger/templates/blogger/page.html
{% load static %}

<head>
  <!-- for converting markdown to HTML and back -->
  <script src='https://cdnjs.cloudflare.com/ajax/libs/markdown-it/8.4.2/markdown-it.min.js'></script>
  <!-- <script src='https://unpkg.com/turndown/dist/turndown.js'></script> -->
  <!-- <script src='https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js'></script> -->
  <link rel='stylesheet' type='text/css' href='{% static "blogger/page.css" %}' />
  <link rel='icon' type='image/png' href='https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Banana-Single.jpg/1200px-Banana-Single.jpg'>
  <title> {{ title|safe }} </title>
</head>

<body>
  <!-- display messages -->
  {% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}

  <!-- title + authors (editable with permission, customizable color)-->
  <div id='title-container' class='section' contenteditable='{{ editable }}' style='background-color: {{ color }};'>
    <!-- title -->
    <div id='title' style='display: inline-block;'>
      <h1> {{ title|safe }} </h1>
    </div>
    <!-- authors (plus options defining whether they are editable etc.) -->
    <div class='buttons' contenteditable='false' style='display: inline-block;'>
      {% if admin %}
      <div class='section button low-margin' style='cursor: default;'>
        admin
      </div>
      {% endif %}
      {% for author in authors %}
      <a class='nodecor' href='{% url "blogger:user" author.id %}'>
        <div class='section button low-margin'>
          {{ author.name }}
        </div>
      </a>
      {% endfor %}
      {% if addable %}
      <div id='add' class='section button low-margin' contenteditable='true'>+</div>
      {% endif %}
    </div>
  </div>
  <!-- description (editable with permission, customizable color) -->
  <div id='description' class='section padded' contenteditable='{{ editable|lower }}' style='background-color: {{ desc_color }};'>
    <p> Description </p>
  </div>
  <!-- content (editable with permission) -->
  <div id='content' class='section padded' contenteditable='{{ editable|lower }}'>
    <p> Content </p>
  </div>
  <!-- {% if page_type == 'page' %}
    {% if links %}
      {% for link in links %}
      <a class='nodecor' href='{% url "blogger:link" link.id %}'>
        <div class='link section padded' style='background-color: {{ link.color }};'>
          {% if link.description %}
          <p> Link to {{ link.title }}: {{ link.description|safe }} </p>
          {% else %}
          <p> Link to {{ link.title }} </p>
          {% endif %}
        </div>
      </a>
      {% endfor %}
    {% endif %}
  {% elif page_type == 'link' %}
    {% for page in links %}
    <a class='nodecor' href='{% url "blogger:page" page.id %}'>
      <div class='link section padded' style='background-color: {{ page.color }};'>
        {% if page.description %}
        <p> {{ page.title }}: {{ page.description|safe }} </p>
        {% else %}
        <p> {{ link.title }} </p>
        {% endif %}
      </div>
    </a>
    {% endfor %}
  {% endif %} -->
  <div class='buttons'>
    {% if view %}
    {% else %}
    <!-- set title + authors color -->
    <div id='color' class='section button' contenteditable='{{ editable|lower }}'>{{ color }}</div>
    <!-- set description color -->
    <div id='desc-color' class='section button' contenteditable='{{ editable|lower }}'>{{ desc_color }}</div>
    <!-- 'save changes' button, submits form with values of hidden inputs as
    defined by the Javascript -->
    {% if page_type == 'page' %}
    <form id='save-form' action='{% url "blogger:page" id %}' method='post'>
    {% elif page_type == 'link' %}
    <form id='save-form' action='{% url "blogger:link" id %}' method='post'>
    {% endif %}
      {% csrf_token %}
      <input id='input-title' type='hidden' name='title'>
      <input id='input-desc' type='hidden' name='description'>
      <input id='input-content' type='hidden' name='content'>
      <input id='input-color' type='hidden' name='color'>
      <input id='input-desc-color' type='hidden' name='desc-color'>
      <input id='input-author' type='hidden' name='author'>
      <div id='save' class='section button'>
        Save changes
      </div>
    </form>
    <!-- 'revert changes' button, reloads the page with Javascript  -->
    <div id='revert' class='section button'>
      Revert changes
    </div>
    {% endif %}
    <a href='{% url "blogger:index" %}'>
      <div class='section button'>
        Back to index
      </div>
    </a>
  </div>
  <script>
    // transfer Django template variables to Javascript variables
    var desc_text = `{{ description|safe }}`;
    var content_text = `{{ content|safe }}`;
    var editable = {{ editable|lower }};
    var addable = {{ addable|lower }};
  </script>
  <script src='{% static "blogger/page.js" %}'></script>
</body>

blogger/templates/blogger/profile.html
{% load static %}

<head>
  <link rel='stylesheet' type='text/css' href='{% static "blogger/blocks.css" %}' />
  <link rel='icon' type='image/png' href='https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Banana-Single.jpg/1200px-Banana-Single.jpg'>
  <title> profile </title>
</head>

<body class='flex'>
  <!-- display messages -->
  {% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}

  <!-- display name + username -->
  <div class='main section padded'>
    <h1> {{ name }} </h1>
    <p> Username: {{ username }} </p>
  </div>
  <!-- forms to change things (with permission) -->
  {% if change %}
  <div class='main section padded' style='display: flex; flex-direction: row; justify-content: space-around; align-items: center;'>
    <form action='{% url "blogger:profile" %}' method='post' autocomplete='off'>
      {% csrf_token %}
      {{ name_form|linebreaks }}
      <input type='submit' name='name_form' value='Change'>
    </form>
    <form action='{% url "blogger:profile" %}' method='post' autocomplete='off'>
      {% csrf_token %}
      {{ password_form|linebreaks }}
      <input type='submit' name='password_form' value='Change'>
    </form>
  </div>
  {% endif %}

  <div class='buttons'>
    <!-- decide whether to go back to index or a specific page (the page the
    user was last on) -->
    {% if page %}
      {% if link %}
        <a href='{% url "blogger:link" page %}'>
          <div class='section button'>
            Back to link page
          </div>
        </a>
      {% else %}
        <a href='{% url "blogger:page" page %}'>
          <div class='section button'>
            Back to page
          </div>
        </a>
      {% endif %}
    {% else %}
    <a href='{% url "blogger:index" %}'>
      <div class='section button'>
        Back to index
      </div>
    </a>
    {% endif %}

    <!-- delete account (with permission) -->
    {% if change %}
    <a href='{% url "blogger:delete" %}'>
      <div class='section button'>
        Delete account
      </div>
    </a>
    {% endif %}
  </div>
</body>